# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (username.github.io) then use these settings:
#url: "http://username.github.io"
#baseurl: ""

# If you are building a GitHub project page then use these settings:
url: "https://jasdumas.github.io"
baseurl: ""

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Jasmine Daly

# Short description of your site
description: Experienced Data Scientist & R Programmer

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: /img/new_avatar.png

# List of links in the navigation bar
navbar-links:
  Blog: ""
  Projects: "projects"
  Data Science Resources:
    - Data Science Links: "ds-resources"
    - FAQ: "faq"
    - R Tutorials: "r-papers"
    - Python Tutorials: "py-papers"
    - Course Notes: "course-notes"
  About Me: 
    - About Me: "aboutme"
    - Resume/CV: "resume"
    - Consulting: "consulting"
    - Speaking: "speaking"
    - Featured Videos: "videos"
nav-search: search


# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Jasmine Daly
  github: jasdumas
  twitter: jasdumas
  linkedin: in/jasminedumas
  stackoverflow: users/4143444/jasmine-dumas
  instagram: jasdumas
  email: jasmine.dumas@gmail.com
  squarecashme: $jasdumas

 
# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: false
  email: true
  twitter: true
  google-plus: false
  github: true
  linkedin: true
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: true
  youtube: false
  spotify: false
  squarecashme: true
  
# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: jasdumas.github.io  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: jasminedaly

# Fill in your Google Analytics ID to track your website using GA
google_analytics: UA-74123437-1

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/New_York"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 7
paginate_path: "/page:num/"
gems:
  - jemoji
  - jekyll-sitemap

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true


# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md
