---
title: "Debugging R"
author: "Jasmine Dumas"
date: "September 20, 2016"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tips & Methodology

 + R is known for having a vibrant open-source community, a steep learning curve, and sometimes cryptic error and warning messages. All of these nuances add up to a great treasure trove of online resources to assist with vexing R code.
 + A tip for debugging your own R code is to try it for 15 minutes and afterwards seek out assistance from teammates.
 + R includes some features for debugging such as the `traceback()` function which gets and print the call stack. The `browser()` function interrupts the execution of an expression allows for further inspection. RStudio even has a menu tab dedicated to debugging.
+ Running R code line by line can help identify a problem in the code.
+ Running the "inside" of a function with supplied arguments can help mediate errors that occur when moving ad hoc code to generalized functions.
+ When in doubt about complex errors on specific use cases: use a simpler data set from `data()` function which shows all of the default data sets that come with R and try to re-create the same error. This is helpful when asking others for help and also removes some of the specific burdens that can be associated with domain-specific data. 
+ Check your data types immediately after reading in the data set. Use `str()` to check for class and object types. Getting a confirmation on class types and objects types can dispel further errors down the road if a function is not applicable to (for example...) [factors](http://www.stat.berkeley.edu/~nolan/stat133/Fall05/lectures/DataTypes4.pdf). Specifying **"stringsAsFactors = FALSE"** can and will be a frequent headache but there are new packages to make it easier: [forcats](https://cran.r-project.org/package=forcats) for working with factors and using the [readr](https://cran.r-project.org/package=readr) package will not automatically convert characters to factor types.
+ To log errors for further analysis and debugging, use the `sink()` function to send R output to a file. The `capture.output()` is also another option for this. 
+ Folders of interests regarding debugging are [debug or errors](//ad1.prod/HIG/PL/CommonShares/PL_CommonShares08/_jasmine/R Documents/debug or errors) and [code snippets](//ad1.prod/HIG/PL/CommonShares/PL_CommonShares08/_jasmine/R Documents/code snippets). The latter folder has person-specific help folders from assisting the team with R debugging and function development.


## Further reading

 + [http://stackoverflow.com/questions/tagged/r](http://stackoverflow.com/questions/tagged/r)
 + [RStudio Support Forum](https://support.rstudio.com/hc/en-us/signin?return_to=https%3A%2F%2Fsupport.rstudio.com%2Fhc%2Fen-us%2Farticles%2F200713843%3Fversion%3D0.99.1249%26mode%3Ddesktop)
 + [Translating Weird R Errors](https://www.r-bloggers.com/translating-weird-r-errors/)


____
fin. 