---
title: "SQL in R: SQLDF Tutorial"
author: "Jasmine Dumas"
date: "August 19, 2016"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
    code_download: true
    fig_width: 9
    fig_height: 6
    theme: flatly
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)

```


## Example Data
```{r, data}
# libraries
library(sqldf)
library(RH2)

data("UCBAdmissions")

# must be a data frame
ucb <- as.data.frame(UCBAdmissions)

sqldf("select * from ucb")

majors <- data.frame(major = c("math", "biology", "engineering", "computer science", "history", "architecture"), Dept = c(LETTERS[1:5], "Other"), Faculty = round(runif(6, min = 10, max = 30)))

sqldf("select * from majors")

```

## General Queries
```{r, general}
# Return Female student admission result
sqldf("select * from ucb where Gender = 'Female'")
# Return the admitted students
sqldf("select * from ucb where Admit = 'Admitted'")
# order admissions per department
sqldf("select * from ucb where Admit = 'Admitted' order by Freq DESC")
# how many departments are in this table
sqldf("select distinct Dept from ucb")

```

## Aggregate Queries
```{r, agg}
# total admitted studets
sqldf("select sum(Freq) from ucb where Admit = 'Admitted'")
# total rejected students
sqldf("select sum(Freq) from ucb where Admit = 'Rejected'")
# return total admitted males
sqldf("select sum(Freq) as total_dudes from ucb where Admit = 'Admitted' AND Gender = 'Male'")
# return total reject females
sqldf("select sum(Freq) as total_ladies from ucb where Admit = 'Rejected' AND Gender = 'Female'")
# average number of admitted student by department (usually mean)
sqldf("select Dept, avg(Freq) as average_admitted from ucb where Admit = 'Admitted' group by Dept")
# how many majors are there
sqldf("select count(major) from majors")
# minimum amount of studets rejected
sqldf("select min(Freq) from ucb where Admit = 'Rejected'")

```

## Wild card match Queries
```{r, wild}
sqldf("select * from ucb where Freq between 20 AND 100")
sqldf("select * from ucb where Gender Like 'Fe%'")
sqldf("select * from ucb where Gender Like '%male%'")
sqldf("select * from ucb where Gender Like 'Ma%'")
sqldf("select * from ucb where Gender = 'Female' AND Freq >= 100 ")
sqldf("select * from ucb where Gender Like '_ale'")
sqldf("select * from ucb where Gender NOT Like 'M_l_'")
```


## Manipulation & Nested Queries
```{r, nest}
# Which department had the most admitted students = A
sqldf("select Dept from ucb where Freq = (select max(Freq) from ucb where Admit = 'Admitted')")

# which department had the most admitted Female student = C
sqldf("select Dept from ucb where Freq = (select max(Freq) from ucb where Gender = 'Female')")

# department with most faculty 
sqldf("select Dept from majors where Faculty = (select max(Faculty) from majors)")

```


## Join Queries
```{r, join}
# join the two tables together by the common key
sqldf("select * from ucb 
      inner join majors on ucb.Dept = majors.Dept")
# join the table on the left with resultant nulls's on the right table
sqldf("select * from ucb left join majors on ucb.Dept = majors.Dept")
# join the table on the right with the left
sqldf("select * from ucb right join majors on ucb.Dept = majors.Dept")

```

## Resources

* [https://cran.r-project.org/web/packages/sqldf/sqldf.pdf](https://cran.r-project.org/web/packages/sqldf/sqldf.pdf)
* [https://github.com/ggrothendieck/sqldf](https://github.com/ggrothendieck/sqldf)
* [http://www.w3schools.com/sql/default.asp](http://www.w3schools.com/sql/default.asp)



fin.
